name: 'Initialize DVC'
description: 'Setup DVC and configure credentials'
inputs:
  DVC_SSH_KEY:
    description: 'SSH Key for DVC'
    required: true
  DVC_SSH_PASSPHRASE:
    description: 'Passphrase for SSH Key'
    required: true
  DTU_PASSWORD:
    description: 'DTU Password'
    required: true
  DVC_SSH_USERNAME:
    description: 'DVC SSH Username'
    required: true
  DVC_SSH_HOSTNAME:
    description: 'DVC SSH Hostname'
    required: true
runs:
  using: "composite"
  steps:
    - uses: iterative/setup-dvc@v2

    - name: Cache DVC .dvc/cache
      uses: actions/cache@v4
      with:
        path: .dvc/cache
        # Key includes OS and hash of all dvc files to invalidate when data changes
        key: dvc-cache-${{ runner.os }}-${{ hashFiles('**/*.dvc', '**/dvc.lock') }}
        restore-keys: |
          dvc-cache-${{ runner.os }}-

    - name: Configure DVC Credentials
      shell: bash
      env:
        SSH_KEY: ${{ inputs.DVC_SSH_KEY }}
        DVC_SSH_PASSPHRASE: ${{ inputs.DVC_SSH_PASSPHRASE }}
        SSH_PASS: ${{ inputs.DTU_PASSWORD }}
        REMOTE_NAME: "hpc_storage"
        DVC_SSH_USERNAME: ${{ inputs.DVC_SSH_USERNAME }}
        DVC_SSH_HOSTNAME: ${{ inputs.DVC_SSH_HOSTNAME }}
      run: |
        # Write the key to a local file in the workspace
        echo "$SSH_KEY" > dvc_key_file

        # Add known host to avoid "Host key verification failed" or interactive prompt
        mkdir -p ~/.ssh
        ssh-keyscan -H "$DVC_SSH_HOSTNAME" >> ~/.ssh/known_hosts

        if [ "$RUNNER_OS" == "Windows" ]; then
          icacls dvc_key_file //inheritance:r
          icacls dvc_key_file //grant:r "$(whoami):F"
        else
          chmod 600 dvc_key_file
        fi

        # Decrypt the key (Remove passphrase)
        if [ -n "$DVC_SSH_PASSPHRASE" ]; then
            # -f: filename, -p: old passphrase, -N: new passphrase (empty)
            ssh-keygen -p -f dvc_key_file -P "$DVC_SSH_PASSPHRASE" -N ""
        fi

        # Configure DVC Locally (Does not affect git tracking)
        # This injects the credentials directly into DVC's runtime config
        dvc remote modify --local $REMOTE_NAME user $DVC_SSH_USERNAME
        dvc remote modify --local $REMOTE_NAME keyfile "$(pwd)/dvc_key_file"
        dvc remote modify --local $REMOTE_NAME password "$SSH_PASS"

        # Use full hostname for DVC remote
        dvc remote modify --local $REMOTE_NAME url "ssh://$DVC_SSH_HOSTNAME/zhome/c3/e/221590/MLOps-storage"
